pipeline:
  identifier: Build_tfahey_jhttp_1703686086184
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: jhttp
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: tfahey/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
